### ISSUE TITLE
Mk3S1 Liquid Fuel Fuselage model glitch

### ISSUE THREAD

**Issue by skppr** [net-lisias-ksp/AirplanePlus#12]
![image](https://github.com/net-lisias-ksp/AirplanePlus/assets/81135395/99eedb4c-c4ec-4577-87f8-3d7507d078cb)
Occurs with the longer one as well.

**Comment by skppr** [comment]
Fixed after installing Firespitter Core (wasn't clear on the github that this is required)

**Comment by Lisias** [comment]
Hi! I finally noticed this, and took some action.

Fixed on commit https://github.com/net-lisias-ksp/AirplanePlus/commit/d46633526053015570afbd48a558d10ec18d5db0
